---
layout: post
title: 'Springboot 事务'
subtitle: '事务提交回滚问题'
date: 2020-2-14
categories: 技术
tags: springboot Transaction
---


# Springboot 事务

今天写项目发现一个问题,在添加用户的功能中，逻辑大概是这样的

```
（添加了事务@Transactional）
查缓存中是否存在用户名（否则继续）
---
添加用户表用户信息
---
添加用户角色表信息
---
将用户名添加缓存
---
```

但这么写存在一个问题，就是如果中间的添加操作存在问题，自动回滚后，数据库没有用户的信息，但是redis中却有，该用户就不能再次注册了，尽管数据库中没有，后来找到了解决办法~~（怪不得代码提示 Alibaba Java Coding GuideLines）~~

## ***\*事务场景中，抛出异常被catch后，如果需要回滚，一定要手动回滚事务。\****

自动提交，手动回滚，大概逻辑是这样的

```
（添加了事务@Transactional）
配置事务管理器
---
查缓存中是否存在用户名（否则继续）
---
try
添加用户表用户信息
添加用户角色表信息
将用户名添加缓存
catch
回滚
删缓存
---
```



代码如图

```java
/**
     * 自动提交，手动回滚
     * @param user
     * @return
     * @throws XJWCException
     */
    @Override
    @Transactional
    public JSONResult insertUser(User user) throws XJWCException {
        // 配置事务策略
        DefaultTransactionDefinition def = new DefaultTransactionDefinition();
        def.setName("transaction");
        def.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRED);
        // 设置状态点
        TransactionStatus status = dataSourceTransactionManager.getTransaction(def);
        //先查询缓存，未命中再查询数据库
        if (redisMapper.hsize(Constant.USER_PHONE_EXIST) != 0) {
            if (redisMapper.hHasKey(Constant.USER_PHONE_EXIST, user.getPhone())) {
                throw new XJWCException("该号码已被注册，请重试");
            }
        } else {
            int num = userMapper.findByPhone(user.getPhone());
            System.out.println(num);
            if (0 < num) {
                throw new XJWCException("该号码已被注册，请重试");
            }
        }
        String id = GetRandom.getUUID();
        user.setUserId(id);
        user.setRole(2);
        //密码加密存储
        Object o = MD5.MD5(user.getPhone(), user.getPassword());
        user.setPassword(String.valueOf(o));
        try{
            userMapper.insertUser(user);
            userMapper.insertUserRole(id, 2);
            redisMapper.hset(Constant.USER_PHONE_EXIST, user.getPhone(), 1);
            logger.info("添加用户成功" + JsonUtil.getJsonString(user));
        } catch (Exception ex) {
            logger.error("添加用户失败 ： " + ex.getMessage());
            dataSourceTransactionManager.rollback(status);
            redisMapper.hdel(Constant.USER_PHONE_EXIST, user.getPhone());
            throw new XJWCException("添加用户失败，请重新尝试！");
        }
        return JSONResult.ok(1);
    }
```

## 阿里爸爸nb！

~~我还是太菜了~~

**以后会专门写一篇文章来说一下事务**